version: '3.5'
services:
  redis:
    image: "redis:alpine"
    expose:
        - 6379
    ports:
      - "6379:6379"
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master

  backend:
    build: /root/projects/report_autification_backend/report_autification_backend/src
    container_name: backend
    command: bash -c 'uvicorn main:app --host 0.0.0.0'
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SUPERUSER_NAME=${SUPERUSER_NAME}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - AWS_URI=${AWS_URI}
      - AWS_ACCCESS_KEY=${AWS_ACCCESS_KEY}
      - AWS_SERVICE_NAME=${AWS_SERVICE_NAME}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - FILE_COUNT=5
      - FILE_SIZE=10
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis

  frontend:
    build: /root/projects/report_autification_front/report_autification_front
    container_name: frontend
    environment:
      - REACT_APP_SERVER_IP=http://localhost:8000/
      - DISABLE_ESLINT_PLUGIN=true npm start
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  server:
    restart: always
    image: nginx
    container_name: nginx_server
    volumes:
      - ./cert/key.key:/etc/ssl/key.key
      - ./cert/crt.crt:/etc/ssl/crt.crt
      - ./server/conf.d:/etc/nginx/conf.d
      - ./frontend/build:/usr/share/nginx/html
    links:
      - backend:backend
      - frontend:frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

